version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6380:6379"  # Map host port 6380 to container port 6379

  web:
    build: .
    container_name: distribute_word_web
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env
  worker:
    build: .
    container_name: distribute_word_worker
    command: rq worker --url ${REDIS_URL}
    depends_on:
      - redis
    env_file:
      - .env