---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: local-dock-distribute-word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: local/web:latest  # replace with your actual built image
          imagePullPolicy: IfNotPresent
          command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: web-env
            - configMapRef:
                name: web-config
          env:
            - name: REDIS_URL
              value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: local-dock-distribute-word
spec:
  selector:
    app: web
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
