---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: local-dock-distribute-word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: local/worker:latest  # replace with your built image
          imagePullPolicy: IfNotPresent
          command: ["rq", "worker", "--url", "redis://redis:6379"]
          # envFrom:
          #   - secretRef:
          #       name: web-env
          #   - configMapRef:
          #       name: web-config
