apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
    scrape_configs:
      - job_name: 'web'
        static_configs:
          - targets: ['{{ .Values.web.appLabel }}:{{ .Values.web.port }}']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prometheus.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.appLabel }}
    spec:
      containers:
        - name: {{ .Values.prometheus.containerName }}
          image: {{ .Values.prometheus.image }}:{{ .Values.prometheus.tag }}
          imagePullPolicy: {{ .Values.prometheus.imagePullPolicy }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Values.prometheus.name }}-config



